# Site settings
name: Raghav
email: email@raghavendra.me
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, FullStack developer, React, ReactJs, React Native, Python, Cassandra, ElasticSearch, Big Data"
skills: "Technical Architecct at CloudThing Pvt Ltd (Bangalore, India)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/raghavendra-muppalla-97582664/
  - title: medium
    url: https://medium.com/@raghu1286
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
